"use client";

import Image from "next/image";
import Link from "next/link";
import { motion } from "framer-motion";
import { ArrowRight, Award, HandHeart, Handshake, Heart, Landmark, Users } from "lucide-react";
import LeadershipSection from "@/components/about/LeadershipSection";

const focusAreas = [
  { icon: Landmark, title: "Culture & Heritage", description: "Celebrating festivals, traditions, arts and languages that connect generations to their roots and keep our cultural heritage alive." },
  { icon: HandHeart, title: "Service & Volunteering", description: "Giving back through volunteer initiatives, youth engagement, mentorship and programs that support people across Niagara." },
  { icon: Handshake, title: "Partnership", description: "Working alongside local businesses, organizations and community leaders to create opportunities and build a stronger Niagara." },
];

const communities = ["Niagara Falls", "St. Catharines", "Welland", "Niagara-on-the-Lake", "Thorold", "Surrounding Niagara communities"];
const activities = ["Cultural festivals and celebrations", "Wellness and community programs", "Youth activities and mentorship", "Family and community gatherings", "Seniors outreach", "Business and community networking"];

export default function AboutPage() {
  return <main className="bg-[#fffdf8] text-[#0B1F3A]">
    <section className="relative overflow-hidden"><div className="absolute inset-0 bg-cover bg-center" style={{ backgroundImage: "url('/images/nia-hero-background.jpg')" }} /><div className="absolute inset-0" style={{ background: "linear-gradient(90deg, rgba(255,253,248,.99) 0%, rgba(255,253,248,.97) 25%, rgba(255,253,248,.88) 40%, rgba(255,253,248,.6) 55%, rgba(255,253,248,.18) 75%, rgba(255,253,248,0) 100%)" }} /><div className="relative z-10 mx-auto flex min-h-[540px] max-w-7xl items-center px-6 py-20 lg:px-10"><motion.div initial={{ opacity: 0, x: -35 }} animate={{ opacity: 1, x: 0 }} transition={{ duration: .7 }} className="max-w-2xl"><div className="mb-5 flex items-center gap-3"><span className="h-px w-8 bg-orange-500" /><span className="text-[10px] font-bold uppercase tracking-[.3em] text-orange-500">About Niagara Indian Association</span><span className="h-px w-8 bg-green-600" /></div><h1 className="text-5xl font-black leading-[.98] tracking-tight sm:text-6xl lg:text-7xl">Preserving<br /><span className="text-orange-500">Culture.</span><br />Building<br />Community.</h1><p className="mt-7 max-w-xl text-base font-medium leading-7 text-slate-600 sm:text-lg">Connecting the Indian community across Niagara through culture, events, service and meaningful community connections.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/membership" className="inline-flex items-center gap-2 rounded-xl bg-orange-500 px-6 py-3.5 text-sm font-bold text-white shadow-lg shadow-orange-500/20 transition hover:-translate-y-1 hover:bg-orange-600"><span>Become a Member</span><ArrowRight size={16} /></Link><Link href="/events" className="inline-flex items-center gap-2 rounded-xl border border-[#0B1F3A]/20 bg-white px-6 py-3.5 text-sm font-bold text-[#0B1F3A] shadow-sm transition hover:-translate-y-1 hover:shadow-md"><span>See Our Events</span><ArrowRight size={16} /></Link></div></motion.div></div></section>

    <section className="px-6 py-20 sm:px-10 lg:py-28"><div className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-[1.1fr_.9fr] lg:items-center"><motion.div initial={{ opacity: 0, x: -30 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true }} transition={{ duration: .7 }}><div className="mb-4 flex items-center gap-3"><span className="h-px w-8 bg-orange-500" /><span className="text-[10px] font-bold uppercase tracking-[.3em] text-orange-500">Who We Are</span></div><h2 className="text-4xl font-black leading-tight sm:text-5xl">A community<br />built around<span className="text-orange-500"> belonging.</span></h2><div className="mt-7 space-y-5 text-base leading-8 text-slate-600"><p>Niagara Indian Association is a non-profit, volunteer-driven organization dedicated to preserving Indian culture, celebrating our heritage and supporting the Indian community across Niagara.</p><p>Founded and powered by volunteers, NIA brings together families, individuals and community members from across the Niagara Region. Throughout the year, we create opportunities to celebrate culture, connect with one another and contribute to the wider community.</p><p>Whether you are new to Canada, raising a family, building your career or simply looking for a way to stay connected to Indian culture, NIA is a place where you can belong.</p></div></motion.div><motion.div initial={{ opacity: 0, x: 30 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true }} transition={{ duration: .7 }} className="relative overflow-hidden rounded-[32px] bg-[#0B1F3A] p-8 shadow-2xl sm:p-10"><div className="absolute -right-24 -top-24 h-64 w-64 rounded-full border-[32px] border-orange-500/15" /><div className="absolute -bottom-28 -left-24 h-72 w-72 rounded-full border-[32px] border-green-600/10" /><div className="relative z-10"><div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-white p-3"><Image src="/images/nia-logo.png" alt="Niagara Indian Association" width={70} height={70} className="h-full w-full object-contain" /></div><p className="mt-8 text-[10px] font-bold uppercase tracking-[.3em] text-orange-400">Across Niagara</p><h3 className="mt-3 text-3xl font-black text-white">One community.<br />Many stories.</h3><p className="mt-5 text-sm leading-7 text-slate-300">Our community spans cities and towns throughout Niagara, bringing together people with shared roots, traditions and a desire to connect.</p><div className="mt-7 grid grid-cols-2 gap-2">{communities.map((community) => <div key={community} className="rounded-xl border border-white/10 bg-white/5 px-3 py-2.5 text-xs font-medium text-slate-300">{community}</div>)}</div></div></motion.div></div></section>

    <section className="bg-slate-50 px-6 py-20 sm:px-10 lg:py-28"><div className="mx-auto max-w-7xl"><motion.div initial={{ opacity: 0, y: 25 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ duration: .6 }}><div className="flex items-center gap-3"><span className="h-px w-8 bg-green-600" /><span className="text-[10px] font-bold uppercase tracking-[.3em] text-green-700">What We Do</span></div><h2 className="mt-4 text-4xl font-black sm:text-5xl">Culture, service and connection.</h2><p className="mt-5 max-w-2xl text-slate-500">Our work brings people together while creating meaningful opportunities to celebrate our heritage and contribute to the Niagara community.</p></motion.div><div className="mt-12 grid gap-5 md:grid-cols-3">{focusAreas.map((area, index) => { const Icon = area.icon; return <motion.div key={area.title} initial={{ opacity: 0, y: 25 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ duration: .5, delay: index * .1 }} className="rounded-[28px] border border-slate-200 bg-white p-8 shadow-sm transition duration-300 hover:-translate-y-1 hover:shadow-xl"><div className="flex h-13 w-13 items-center justify-center rounded-2xl bg-orange-500/10 text-orange-500"><Icon size={24} /></div><h3 className="mt-7 text-xl font-black">{area.title}</h3><p className="mt-4 text-sm leading-7 text-slate-500">{area.description}</p></motion.div>; })}</div></div></section>

    <LeadershipSection />

    <section className="px-6 py-20 sm:px-10 lg:py-28"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><motion.div initial={{ opacity: 0, x: -30 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true }}><div className="flex items-center gap-3"><span className="h-px w-8 bg-orange-500" /><span className="text-[10px] font-bold uppercase tracking-[.3em] text-orange-500">Community Life</span></div><h2 className="mt-4 text-4xl font-black leading-tight sm:text-5xl">Something for<span className="text-orange-500"> everyone.</span></h2><p className="mt-6 text-base leading-8 text-slate-600">Throughout the year, NIA creates opportunities for community members of different ages and backgrounds to participate, connect and contribute.</p></motion.div><div className="grid gap-3 sm:grid-cols-2">{activities.map((activity, index) => <motion.div key={activity} initial={{ opacity: 0, y: 15 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ duration: .4, delay: index * .05 }} className="flex items-center gap-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-green-600/10 text-xs font-black text-green-700">{String(index + 1).padStart(2, "0")}</span><span className="text-sm font-semibold leading-6">{activity}</span></motion.div>)}</div></div></section>

    <section className="bg-[#0B1F3A] px-6 py-20 sm:px-10 lg:py-24"><div className="mx-auto max-w-5xl text-center"><Award className="mx-auto text-orange-400" size={30} /><p className="mt-5 text-[10px] font-bold uppercase tracking-[.3em] text-orange-400">Community Recognition</p><h2 className="mt-4 text-3xl font-black text-white sm:text-4xl">Celebrating those who strengthen our community.</h2><p className="mx-auto mt-5 max-w-3xl text-sm leading-7 text-slate-300">NIA values the leaders, volunteers, elected officials, organizations and community partners who contribute to the growth and success of the Indian community in Niagara.</p><Link href="/gallery" className="mt-8 inline-flex items-center gap-2 rounded-full border border-white/20 bg-white/10 px-6 py-3 text-sm font-bold text-white transition hover:bg-white/20">Explore Community Moments <ArrowRight size={16} /></Link></div></section>

    <section className="px-6 py-20 sm:px-10 lg:py-28"><div className="mx-auto max-w-7xl"><div className="grid gap-6 md:grid-cols-2"><motion.div initial={{ opacity: 0, x: -20 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true }} className="rounded-[28px] border border-slate-200 bg-white p-8 shadow-sm sm:p-10"><Users className="text-orange-500" size={28} /><h2 className="mt-6 text-2xl font-black">Be part of the community.</h2><p className="mt-4 text-sm leading-7 text-slate-500">NIA membership gives community members an opportunity to stay connected, participate in cultural events, discover networking opportunities and contribute through volunteer programs.</p><Link href="/membership" className="mt-7 inline-flex items-center gap-2 rounded-full bg-orange-500 px-5 py-3 text-sm font-bold text-white transition hover:bg-orange-600">Become a Member <ArrowRight size={16} /></Link></motion.div><motion.div initial={{ opacity: 0, x: 20 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true }} className="rounded-[28px] bg-slate-50 p-8 sm:p-10"><Handshake className="text-green-600" size={28} /><h2 className="mt-6 text-2xl font-black">Support the community.</h2><p className="mt-4 text-sm leading-7 text-slate-500">Local businesses and organizations play an important role in helping NIA create meaningful experiences and community initiatives. We are grateful for every partnership that helps our community grow.</p><Link href="/contact" className="mt-7 inline-flex items-center gap-2 rounded-full border border-[#0B1F3A]/20 px-5 py-3 text-sm font-bold text-[#0B1F3A] transition hover:bg-[#0B1F3A] hover:text-white">Partner With NIA <ArrowRight size={16} /></Link></motion.div></div></div></section>

    <section className="px-6 pb-20 sm:px-10 lg:pb-28"><motion.div initial={{ opacity: 0, y: 25 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className="mx-auto max-w-6xl overflow-hidden rounded-[32px] bg-[#0B1F3A] px-7 py-14 text-center shadow-2xl sm:px-12"><Heart className="mx-auto text-orange-400" size={24} /><p className="mt-5 text-[10px] font-bold uppercase tracking-[.3em] text-orange-400">Niagara Indian Association</p><h2 className="mt-4 text-3xl font-black text-white sm:text-4xl">There&apos;s a place for you at NIA.</h2><p className="mx-auto mt-5 max-w-2xl text-sm leading-7 text-slate-300">Join a community that celebrates where we come from, contributes to where we live and builds connections for the future.</p><div className="mt-8 flex flex-wrap justify-center gap-3"><Link href="/membership" className="inline-flex items-center gap-2 rounded-full bg-orange-500 px-6 py-3.5 text-sm font-bold text-white transition hover:bg-orange-600">Become a Member <ArrowRight size={16} /></Link><Link href="/contact" className="inline-flex items-center gap-2 rounded-full border border-white/20 bg-white/10 px-6 py-3.5 text-sm font-bold text-white transition hover:bg-white/20">Get Involved <ArrowRight size={16} /></Link></div></motion.div></section>
  </main>;
}
